exercise: ex18.o compress.o
	gcc ex18.o compress.o -o exercise

ex18.0:
	gcc -c ex18.c -o ex18.0

compress.o:
	gcc -c compress.c -o compress.o

run: exercise
	./exercise

clear:
	rm -f ex18.o compress.o
	
	
