exercise: print_array.o ex03.o
	gcc print_array.o ex03.o -o exercise

print_array.o:
	gcc -c print_array.c -o print_array.o

ex03.o:
	gcc -c ex03.c -o ex03.o

run:
	./exercise

clear:
	rm -f print_array.o ex03.o
